name: Build APK with Buildozer

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Android NDK manually (r25b)
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
          unzip ndk.zip -d $HOME/.buildozer/android/platform
          mv $HOME/.buildozer/android/platform/android-ndk-r25b $HOME/.buildozer/android/platform/android-ndk-r25b-linux

      - name: Build APK using Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dicom-viewer-apk
          path: bin/*.apk
