name: Build Android APK

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build with Buildozer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools

      - name: Fix setuptools + pip
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "setuptools>=67,<70" setuptools-scm

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dicomlator.apk
          path: bin/*.apk
