on: [push, pull_request]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Buildozer
      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: test_app
          buildozer_version: stable

      - name: Upload artifacts
      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          name: MyApp-APK
          path: ${{ steps.buildozer.outputs.filename }}
